backend:
  replicas: 2
  image: final-project-backend:latest
  containerPort: 8081
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1000m"
  env:
    SPRING_DB_HOST: "10.0.0.5"
    SPRING_DB_PORT: "5432"
    SPRING_DB_NAME: "orquestas"
    SPRING_DB_USER: "vsanchez"
    SPRING_DB_PASSWORD: "mypassword"
  service:
    port: 8081
    type: LoadBalancer

frontend:
  replicas: 2
  image: final-project-frontend:latest
  containerPort: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  service:
    port: 80
    type: LoadBalancer
