- name: Backup
  hosts: bd
  become: true
  vars:
    postgres_user: "postgres"
    postgres_db: "orquestas"
    backup_file: "/var/backups/postgres/backup_{{ ansible_date_time.date }}.sql.gz.enc"
    encryption_key: "G7x!#aB12$vf@kT"
    local_backup_dir: "/backups"
    ansible_user: "adminuser"
    azure_container_name: "bdbackups"
    azure_account_name: "stavsanchezdvfinlab"
  environment:
    ARM_CLIENT_ID: "{{ lookup('env', 'ARM_CLIENT_ID') }}"
    ARM_CLIENT_SECRET: "{{ lookup('env', 'ARM_CLIENT_SECRET') }}"
    ARM_SUBSCRIPTION_ID: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"
    ARM_TENANT_ID: "{{ lookup('env', 'ARM_TENANT_ID') }}"
    POSTGRE_USER: "{{ lookup('env', 'POSTGRE_USER') }}"
    POSTGRE_PASSWORD: "{{ lookup('env', 'POSTGRE_PASSWORD') }}"
    DB_NAME: "{{ lookup('env', 'DB_NAME') }}"

  tasks:
    - name: Obtener una lista de bases de datos existentes
      community.postgresql.postgresql_info:
        login_host: "localhost"
        login_user: "{{ lookup('env', 'POSTGRE_USER') }}"
        login_password: "{{ lookup('env', 'POSTGRE_PASSWORD') }}"
      register: db_info
    
    - name: Traer backup y usarlo para restaurar la base de datos
      shell: |
        az storage blob download \
          --container-name "{{ azure_container_name }}" \
          --account-name "{{ azure_account_name }}" \
          --file "{{ local_backup_dir }}/backup_{{ ansible_date_time.date }}.sql.gz.enc" \
          --name "backup-{{ ansible_date_time.date }}.sql.gz.enc"
      environment:
        AZURE_CLIENT_ID: "{{ lookup('env', 'ARM_CLIENT_ID') }}"
        AZURE_CLIENT_SECRET: "{{ lookup('env', 'ARM_CLIENT_SECRET') }}"
        AZURE_SUBSCRIPTION_ID: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"
        AZURE_TENANT_ID: "{{ lookup('env', 'ARM_TENANT_ID') }}"
      register: download_output
      failed_when: "'ERROR' in download_output.stdout"
      when: "'{{ lookup('env', 'DB_NAME') }}' not in db_info.databases"

    - name: Actualizar la caché de paquetes
      apt:
        update_cache: yes
      become: true

    - name: Crear el directorio de backups si no existe
      file:
        path: "/var/backups/postgres"
        state: directory
        mode: '0755'

    - name: Dump y cifrar la base de datos PostgreSQL
      shell: |
        pg_dump -U {{ postgres_user }} {{ postgres_db }} | gzip | openssl enc -aes-256-cbc -salt -out {{ backup_file }} -k "{{ encryption_key }}"
      environment:
        PGPASSWORD: "mypassword"
      register: backup_result

    - name: Verificar si el dump y cifrado fue exitoso
      debug:
        msg: "Backup creado correctamente en {{ backup_file }}"
      when: backup_result.rc == 0

    - name: Crear el directorio local de backups si no existe
      local_action:
        module: file
        path: "{{ local_backup_dir }}"
        state: directory
        mode: '0777'

    - name: Ajustar permisos del archivo de backup
      file:
        path: "{{ backup_file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0777'
      become: true

    - name: Traer el backup al controlador local
      fetch:
        src: "{{ backup_file }}"
        dest: "{{ local_backup_dir }}/"
        flat: yes
      become: true

    - name: Confirmar la transferencia del archivo al controlador local
      debug:
        msg: "Backup transferido correctamente al controlador local en {{ local_backup_dir }}/{{ backup_file | basename }}"

    - name: Subir el archivo de backup al contenedor de Azure
      shell: |
        az storage blob upload \
          --container-name "{{ azure_container_name }}" \
          --account-name "{{ azure_account_name }}" \
          --file "{{ local_backup_dir }}/{{ backup_file | basename }}" \
          --name "backup-{{ ansible_date_time.date }}.sql.gz.enc"
      environment:
        AZURE_CLIENT_ID: "{{ lookup('env', 'ARM_CLIENT_ID') }}"
        AZURE_CLIENT_SECRET: "{{ lookup('env', 'ARM_CLIENT_SECRET') }}"
        AZURE_SUBSCRIPTION_ID: "{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}"
        AZURE_TENANT_ID: "{{ lookup('env', 'ARM_TENANT_ID') }}"
      register: upload_output
      failed_when: "'ERROR' in upload_output.stdout"

    - name: Confirmar la subida a Azure
      debug:
        msg: "Backup subido correctamente al contenedor de Azure."
