- name: Backup
  hosts: bd
  become: true
  tasks:

    - name: Crear directorio para backups
      file:
        path: "/var/backups/postgresql"
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Realizar el backup de la base de datos
      command:
        cmd: >
          pg_dump -U {{ db_user }} -h {{ db_host }} {{ db_name }} > /var/backups/postgresql/{{ db_name }}_{{ ansible_date_time.date }}.sql
      become_user: postgres

    - name: Confirmar que el archivo de backup se creó
      stat:
        path: "/var/backups/postgresql/{{ db_name }}_{{ ansible_date_time.date }}.sql"
      register: backup_status

    - name: Mostrar resultado del backup
      debug:
        msg: >
          El backup se ha creado correctamente en
          /var/backups/postgresql/{{ db_name }}_{{ ansible_date_time.date }}.sql
      when: backup_status.stat.exists