---
- name: Instalar PostgreSQL
  hosts: all
  become: yes
  tasks:
    - name: Actualizar el índice de paquetes
      apt:
        update_cache: yes

    - name: Instalar las dependencias necesarias
      apt:
        name: 
          - wget
          - ca-certificates
        state: present

    - name: Agregar el repositorio oficial de PostgreSQL
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        state: present
        filename: "pgdg"

    - name: Agregar la clave GPG de PostgreSQL
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Actualizar el índice de paquetes (de nuevo)
      apt:
        update_cache: yes

    - name: Instalar PostgreSQL
      apt:
        name: 
          - postgresql
          - postgresql-contrib
        state: present

    - name: Asegurarse de que PostgreSQL esté habilitado y en ejecución
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Crear un usuario de PostgreSQL (opcional)
      become_user: postgres
      shell: |
        psql -c "DO \$\$ BEGIN
                  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ postgres_user }}') THEN
                      CREATE ROLE {{ postgres_user }} LOGIN PASSWORD '{{ postgres_password }}';
                      ALTER ROLE {{ postgres_user }} CREATEDB;
                  END IF;
                 END \$\$;"

  vars:
    postgres_user: "userpostgres"
    postgres_password: "admin123"
