- name: Instalar PostgreSQL
  hosts: all
  become: yes
  vars:
    postgres_user: "userpostgres"
    postgres_password: "admin123"
  tasks:
    - name: Actualizar el índice de paquetes
      apt:
        update_cache: yes
    
    - name: Instalar los paquetes necesarios
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    - name: Detectar la versión instalada de PostgreSQL
      command: "psql -V"
      register: postgres_version_output

    - name: Asegurarse de que PostgreSQL esté habilitado y en ejecución
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Reiniciar PostgreSQL
      become: true
      service:
        name: postgresql
        state: restarted
    
