- name: Instalar y configurar PostgreSQL con usuario y base de datos
  hosts: all
  become: yes
  vars:
    postgres_user: "userparaback"  # Nombre del usuario que quieres crear
    postgres_password: "admin123" # Contraseña para el usuario
    db_name: "dbback"           # Nombre de la base de datos
  tasks:
    - name: Actualizar el índice de paquetes
      apt:
        update_cache: yes

    - name: Instalar PostgreSQL y dependencias
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    - name: Asegurarse de que el servicio PostgreSQL está iniciado
      service:
        name: postgresql
        state: started
        enabled: yes
    - name: Crear base de datos
      postgresql_db:
        name: "{{ db_name }}"
        owner: "postgres" 
        state: present
      become_user: postgres

    - name: Crear usuario de PostgreSQL
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        state: present
      become_user: postgres

    - name: Asignar privilegios al usuario para la base de datos
      postgresql_privs:
        db: "{{ db_name }}"
        privs: "ALL"
        type: database
        roles: "{{ postgres_user }}"
      become_user: postgres
