- name: Instalar PostgreSQL
  hosts: all
  become: yes
  vars:
    postgres_user: "userpostgres"
    postgres_password: "admin123"
  tasks:
    - name: Actualizar el índice de paquetes
      apt:
        update_cache: yes
    
    - name: Instalar los paquetes necesarios
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present

    - name: Detectar la versión instalada de PostgreSQL
      command: "psql -V"
      register: postgres_version_output

    - name: Extraer versión principal de PostgreSQL
      set_fact:
        postgresql_version: "{{ postgres_version_output.stdout.split()[2].split('.')[0] }}"

    - name: Asegurarse de que PostgreSQL esté habilitado y en ejecución
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Cambiar configuración de PostgreSQL pg_hba.conf
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
        insertafter: '^#.*local.*all.*postgres'
        line: 'local   all   postgres   md5'
        state: present
    - name: Reiniciar PostgreSQL
      become: true
      service:
        name: postgresql
        state: restarted
    
    - name: Crear usuario PostgreSQL
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: SUPERUSER
        state: present


    - name: Reiniciar PostgreSQL
      become: true
      service:
        name: postgresql
        state: restarted
