name: ansible

on:
  workflow_call:

jobs:
  install-ansible:
    runs-on: self-hosted

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Actualizar y actualizar el sistema
      - name: Update and Upgrade System
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade

      # Paso 3: Instalar dependencias necesarias
      - name: Install Required Dependencies
        run: |
          sudo apt-get install -y software-properties-common

      # Paso 4: Agregar el repositorio de Ansible
      - name: Add Ansible PPA
        run: |
          sudo add-apt-repository --yes --update ppa:ansible/ansible

      # Paso 5: Instalar Ansible
      - name: Install Ansible
        run: |
          sudo apt-get install -y ansible

      # Paso 6: Verificar instalación de Ansible
      - name: Verify Ansible Installation
        run: ansible --version

      # Paso 7: Instalar rol de Ansible desde Galaxy
      - name: Install Ansible Galaxy Role
        run: ansible-galaxy role install geerlingguy.postgresql

      # Paso 8: Instalar colección de Ansible para Azure
      - name: Install Azure Collection
        run: ansible-galaxy collection install azure.azcollection

  ejecutaransible:
    needs: install-ansible
    uses: ./.github/workflows/postgre.yml
    with:
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      AZURE_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      AZURE_TENANT: ${{ secrets.ARM_TENANT_ID }}
