name: backup

on:
  workflow_dispatch:

jobs:
  callBackup:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: ls
        run: ls

      - name: llamar al archivo de backup
        working-directory: ansible    
        run: |
          ansible-playbook backup.yaml -i inventory.ini
        env:
          AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          AZURE_TENANT: ${{ secrets.ARM_TENANT_ID }}
          POSTGRE_USER: ${{ secrets.POSTGRE_USER }}
          POSTGRE_PASSWORD: ${{ secrets.POSTGRE_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}