name: backup

on:
  workflow_dispatch:

jobs:
  callBackup:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: ls
        run: ls
      
    
      - name: llamar al archivo de backup
        working-directory: ansible    
        run: |
          export AZURE_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}
          export AZURE_SECRET=${{ secrets.ARM_CLIENT_SECRET }}
          export AZURE_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
          export AZURE_TENANT=${{ secrets.ARM_TENANT_ID }}
          export POSTGRE_USER=${{ secrets.POSTGRE_USER }}
          export POSTGRE_PASSWORD=${{ secrets.POSTGRE_PASSWORD }}
          export DB_NAME=${{ secrets.DB_NAME }}
          ansible-playbook backup.yaml -i inventory.ini --extra-vars "azure_client_id=${{ secrets.ARM_CLIENT_ID }} azure_secret=${{ secrets.ARM_CLIENT_SECRET }} azure_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }} azure_tenant=${{ secrets.ARM_TENANT_ID }} postgre_user=${{ secrets.POSTGRE_USER }} postgre_password=${{ secrets.POSTGRE_PASSWORD }} db_name=${{ secrets.DB_NAME }}"
