name: backup

on:
  workflow_dispatch:

jobs:
  callBackup:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: ls
        run: ls

      - name: llamar al archivo de backup
        working-directory: ansible    
        run: |
          ansible-playbook backup.yaml -i inventory.ini
      - name: Set up Microsoft repository
        run: |
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
          sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

      - name: Update package list and install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli
        
      - name: Instalar az copy
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
          tar -xvf azcopy.tar.gz
          sudo mv ./azcopy_linux_amd64_*/azcopy /usr/local/bin/
          azcopy --version


      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
        env:
          AZURE_CREDENTIALS: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }

      - name: Az copy login
        run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} --password ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

     # - name: Subir archivo a Azure
     #  run: |
     #     azcopy copy "/backup/backup_2024-11-23.sql.gz.enc" "https://stavsanchezdvfinlab.blob.core.windows.net/backups/backup_2024-11-23.sql.gz.enc" --recursive
     

      - name: az blob update
        run: |
          az storage blob upload --account-name stavsanchezdvfinlab --container-name backups --file /backups/backup_2024-11-23.sql.gz.enc --name backup_2024-11-23.sql.gz.enc
        env:
         DATE: $(date +%Y-%m-%d)