name: backup

on:
  workflow_dispatch:

jobs:
  callBackup:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: ls
        run: ls
      
      - name: instalar az cli
        run: sudo apt-get install -y azure-cli
      
      

      # Paso 3: Login en Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
        env:
          AZURE_CREDENTIALS: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }
    
      - name: llamar al archivo de backup
        working-directory: ansible    
        run: |
          ansible-playbook backup.yaml -i inventory.ini
         
