name: backup

on:
  workflow_dispatch:

jobs:
  callBackup:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: ls
        run: ls
      
      - name: instalar az cli
        run: sudo apt-get install -y azure-cli
      
      - name: Login a Azure con mis secretos
        run: az login \
            --username $AZURE_CLIENT_ID \
          --password $AZURE_SECRET \
          --tenant $AZURE_TENANT
    
      - name: llamar al archivo de backup
        working-directory: ansible    
        run: |
          ansible-playbook backup.yaml -i inventory.ini
         
