name: backup

on:
  workflow_dispatch:

jobs:
  callBackup:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: ls
        run: ls
      
      - name: instalar az cli
        run: sudo apt-get install -y azure-cli
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
    
      - name: llamar al archivo de backup
        working-directory: ansible    
        run: |
          ansible-playbook backup.yaml -i inventory.ini
         
