name: Reusable Subir imagen

on:
  workflow_call:
    inputs:
      VERSION_CHART:
        required: true
        type: string
      MICROSERVICE:
        required: true
        type: string
      
jobs:
  subirImagen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout otro repo
        uses: actions/checkout@v3
        with:
          repository: stemdo-labs/final-project-gestion-rrhh-${{ github.event.inputs.MICROSERVICE }}
          ref: main
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
        env:
          AZURE_CREDENTIALS: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }
      
      - name: Azure Container Registry Login
        run: az acr login --name containerregistry.azurecr.io
      
      - name: tagerar la imagen
        run: |
          docker tag imagen-proyecto-${{ github.event.inputs.MICROSERVICE }} containerregistry.azurecr.io/imagen-proyecto-${{ github.event.inputs.MICROSERVICE }}:${{ github.event.inputs.VERSION_CHART }}
          docker push containerregistry.azurecr.io/imagen-proyecto-${{ github.event.inputs.MICROSERVICE }}:${{ github.event.inputs.VERSION_CHART }}




      
