name: CI
on:
 workflow_call:
   
jobs:
  createInfraestructure:
   uses: ./.github/workflows/infraestructure.yaml
   secrets: inherit
  useAnsible:
   needs: createInfraestructure
   uses: ./.github/workflows/ansible.yaml
   secrets: inherit
  subirachivos:
   uses: ./.github/workflows/subirarchivos.yaml
   secrets: inherit