name: CI
on:
 workflow_call:
   
jobs:
  createInfraestructure:
   uses: ./.github/workflows/infraestructure.yaml
   secrets: inherit
  selfhosted:
   needs: [createInfraestructure]
   uses: ./.github/workflows/selfhosted.yaml
   secrets: inherit
  createAnsible:
   needs: [selfhosted, createInfraestructure]
   uses: ./.github/workflows/ansible.yaml
   secrets: inherit