name: postgre

on:
  workflow_dispatch:
    
jobs:
  install-postgre:    
    runs-on: self-hosted
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v3
      - name: entrar a los archivos de ansible
        run: cd ansible

      - name: Agregar contraseña del secret
        run: |
          echo password > secreto.txt

      - name: ls
        run: ls

      - name: ejecutar playbook
        working-directory: ansible
        run: |
          ansible-playbook main.yaml -i inventory.ini --vault-password-file secreto.txt