name: selfhosted
on:
  workflow_call:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh sshpass curl tar 

      - name: Entrar a la máquina virtual
        env:
          SSH_USER: adminuser
          SSH_IP: 10.0.0.5
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_IP" << 'EOF'
            # Crear carpeta para el runner
            mkdir -p actions-runner && cd actions-runner

            # Descargar el paquete del runner
            curl -o actions-runner-linux-x64-2.320.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz


            # Extraer el instalador
            tar xzf ./actions-runner-linux-x64-2.320.0.tar.gz

            # Configurar el runner
            ./config.sh --url https://github.com/stemdo-labs/final-project-exercise-ValentinoSanchez00 --token ${{ secrets.RUNNER_TOKEN }}

            # Iniciar el runner
            ./run.sh
          EOF
