name: subirarchivos del chart

on:
  workflow_call:
    inputs:
      MICROSERVICE:
        required: true
        type: string
      VERSION_CHART:
        required: true
        type: string
    secrets:
      TOKEN_GITHUB:
        required: true
      HARBOR_PASSWORD:
        required: true
jobs:
  empaquetarysubir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another repository
        uses: actions/checkout@v3
        with:
          repository: stemdo-labs/final-project-exercise-ValentinoSanchez00
          token: ${{ secrets.TOKEN_GITHUB }}
        
      
      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Empaquetar
        run: |
          cd charts/
          helm package ./chart-${{ inputs.MICROSERVICE }} 

      - name: Subir
        env:
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
          NAME_CHART: ${{ inputs.MICROSERVICE }}
        run: |
          cd charts/
          ls
          CHART_FILE=$(ls -t *${NAME_CHART}-*.tgz | head -n 1)
          echo "Subiendo chart ${CHART_FILE}"
          helm registry login harbor.codeops.es -u vsanchez -p $HARBOR_PASSWORD
          helm push $CHART_FILE oci://harbor.codeops.es/vsanchez
