name: subirarchivos del chart

on:
  workflow_call:
jobs:
  empaquetarysubir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Replace Variables in chart.yaml
        run: |
          cd charts/chart-proyecto
          sed -i "s/'{{NAME_CHART}}'/${{ env.NAME_CHART }}/g" Chart.yaml
          sed -i "s/'{{VERSION_CHART}}'/${{ env.VERSION_CHART }}/g" Chart.yaml
        env:
          NAME_CHART: ${{ vars.NAME_CHART }}
          VERSION_CHART: ${{ vars.VERSION_CHART }}

      - name: Empaquetar
        env:
          NAME_CHART: ${{ vars.NAME_CHART }}
          VERSION_CHART: ${{ vars.VERSION_CHART }}
        run: |
          cd charts/chart-proyecto
          helm package . --version $VERSION_CHART --app-version $VERSION_CHART

      - name: Subir
        env:
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
          NAME_CHART: ${{ vars.NAME_CHART }}
          VERSION_CHART: ${{ vars.VERSION_CHART }}
        run: |
          cd charts/chart-proyecto
          ls
          helm registry login -u vsanchez -p $HARBOR_PASSWORD harbor.codeops.es
          helm push ${NAME_CHART}-${VERSION_CHART}.tgz oci://harbor.codeops.es:443/vsanchez
