name: Reusable Subir imagen

on:
  workflow_call:
    inputs:
      VERSION_CHART:
        required: true
        type: string
      MICROSERVICE:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      
jobs:
  subirImagen:
    runs-on: runner-stemdo-labs
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: ls
        run: ls
      
      - name: echo secrets
        run: |
          echo "ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}"
          echo "ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}"
          echo "ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}"
          echo "ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}"
      
      - name: Install Azure
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }

      - name: Azure Container Registry Login
        uses: docker/login-action@v3
        with:
          registry: containerregistryvsanchez.azurecr.io
          username: ${{ secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}
      
      - name: Construir imagen
        run: |
          docker build -t imagen-proyecto-${{ inputs.MICROSERVICE }} .

      - name: Extraer versión desde package.json (Frontend)
        if: ${{ inputs.MICROSERVICE == 'frontend' }}
        uses: ./.github/actions/packaje.yaml
        id: frontend-version
        with:
          path: ./package.json

      
      - name: Extraer versión desde pom.xml (Backend)
        if: ${{ inputs.MICROSERVICE == 'backend' }}
        uses: ./.github/actions/pom.yaml
        id: backend-version
        with:
          path: ./pom.xml
        
      - name: taggear la imagen
        if: ${{ inputs.MICROSERVICE == 'frontend' }}
        run: |
          docker tag imagen-proyecto-${{ inputs.MICROSERVICE }} containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.frontend-version.outputs.version }}
      
      - name: taggear la imagen
        if: ${{ inputs.MICROSERVICE == 'backend' }}
        run: |
          docker tag imagen-proyecto-${{ inputs.MICROSERVICE }} containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.backend-version.outputs.version }}
      
      - name: Pushear imagen (Frontend)
        if: ${{ inputs.MICROSERVICE == 'frontend' }}
        run: |
          docker push containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.frontend-version.outputs.version }}

      - name: Pushear imagen (Backend)
        if: ${{ inputs.MICROSERVICE == 'backend' }}
        run: |
          docker push containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.backend-version.outputs.version }}