name: Reusable Subir imagen

on:
  workflow_call:
    inputs:
      VERSION_CHART:
        required: true
        type: string
      MICROSERVICE:
        required: true
        type: string
      CLIENT_ID:
        required: true
        type: string
      CLIENT_SECRET:
        required: true
        type: string
      TENANT_ID:
        required: true
        type: string
      SUBSCRIPTION_ID:
        required: true
        type: string
      
jobs:
  subirImagen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: ls
        run: ls
      
      - name: echo secrets
        run: |
          echo "ARM_CLIENT_ID: ${{ inputs.ARM_CLIENT_ID }}"
          echo "ARM_CLIENT_SECRET: ${{ inputs.ARM_CLIENT_SECRET }}"
          echo "ARM_TENANT_ID: ${{ inputs.ARM_TENANT_ID }}"
          echo "ARM_SUBSCRIPTION_ID: ${{ inputs.ARM_SUBSCRIPTION_ID }}"
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ inputs.ARM_CLIENT_ID }}",
              "clientSecret": "${{ inputs.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ inputs.ARM_TENANT_ID }}",
              "subscriptionId": "${{ inputs.ARM_SUBSCRIPTION_ID }}"
            }


      
      - name: Azure Container Registry Login
        run: az acr login --name containerregistry.azurecr.io
      
      - name: tagerar la imagen
        run: |
          docker tag imagen-proyecto-${{ inputs.MICROSERVICE }} containerregistry.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ inputs.VERSION_CHART }}
          docker push containerregistry.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ inputs.VERSION_CHART }}




      
