name: Reusable Subir Imagen

on:
  workflow_call:
    inputs:
      MICROSERVICE:
        required: true
        type: string
      DB_HOST: 
        required: true
        type: string
      DB_PORT: 
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:  
        required: true
      DB_NAME:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }} 

jobs:
  testFrontend:
    if: ${{ inputs.MICROSERVICE == 'frontend' && $ENVIRONMENT == 'production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3


      - name: Test frontend
        run: |
          echo "Configurando y ejecutando linter"
          npm install eslint --save-dev
          npx eslint --init
          npx eslint . --ext .js,.jsx,.ts,.tsx
  
  testBackend:
    if: ${{ inputs.MICROSERVICE == 'backend' && $ENVIRONMENT == 'production' }}
    runs-on: ubuntu-latest
    env:
      SPRING_DB_HOST: ${{ inputs.DB_HOST }}
      SPRING_DB_PORT: ${{ inputs.DB_PORT }}
      SPRING_DB_NAME: ${{ secrets.DB_NAME }}
      SPRING_DB_USER: ${{ secrets.DB_USER }}
      SPRING_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

  subirImagen:
    needs: [testFrontend,testBackend]
    if: always()
    environment: $ENVIRONMENT 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      
      - name: Test backend
        if: ${{ inputs.MICROSERVICE == 'backend'&& $ENVIRONMENT == 'production' }}
        run: |

      - name: Mostrar archivos
        run: ls

      - name: Mostrar secretos
        run: |
          echo "ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}"
          echo "ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}"
          echo "ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}"
          echo "ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Instalar CLI de Azure
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Iniciar sesión en Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}"
            }

      - name: Login en Azure Container Registry
        run: |
          az acr login --name containerregistryvsanchez

      - name: Extraer versión desde package.json (Frontend)
        if: ${{ inputs.MICROSERVICE == 'frontend' }}
        uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/actions/frontend@develop
        id: frontend-version
        with:
          path: ./package.json

      - name: Extraer versión desde pom.xml (Backend)
        if: ${{ inputs.MICROSERVICE == 'backend' }}
        uses: stemdo-labs/final-project-exercise-ValentinoSanchez00/.github/actions/backend@develop
        id: backend-version
        with:
          path: ./pom.xml

      - name: Construir imagen
        run: |
          docker build -t imagen-proyecto-${{ inputs.MICROSERVICE }} .

      - name: Etiquetar la imagen (Frontend)
        if: ${{ inputs.MICROSERVICE == 'frontend' }}
        run: |
          docker tag imagen-proyecto-${{ inputs.MICROSERVICE }} containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.frontend-version.outputs.version }}

      - name: Etiquetar la imagen (Backend)
        if: ${{ inputs.MICROSERVICE == 'backend' }}
        run: |
          docker tag imagen-proyecto-${{ inputs.MICROSERVICE }} containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.backend-version.outputs.version }}

      - name: Pushear imagen (Frontend)
        if: ${{ inputs.MICROSERVICE == 'frontend' }}
        run: |
          docker push containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.frontend-version.outputs.version }}

      - name: Pushear imagen (Backend)
        if: ${{ inputs.MICROSERVICE == 'backend' }}
        run: |
          docker push containerregistryvsanchez.azurecr.io/imagen-proyecto-${{ inputs.MICROSERVICE }}:${{ steps.backend-version.outputs.version }}
